### ISSUE TITLE
License for the project?

### ISSUE THREAD

**Issue by nlfiedler** [andrenth/erlang-exif#1]
Hi Andre, sorry for having to resort to filing an issue to ask you a question. This project has no license or copyright, and I have forked it, and I would feel better if I could add a license to the fork. I would like to use whatever license you would have picked, had you done so. Could you please let me know what license you would choose for this project? Thanks.

**Comment by andrenth** [comment]
Hi Nathan

You can consider it public domain, and feel free to change it to whatever
you like. I never had the time to work on the library properly, so a new
maintainer is welcome :)

**Comment by nlfiedler** [comment]
Great, thanks!
